// Code generated by mockery v2.43.2. DO NOT EDIT.

package metrics

import mock "github.com/stretchr/testify/mock"

// MockMetricer is an autogenerated mock type for the Metricer type
type MockMetricer struct {
	mock.Mock
}

type MockMetricer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMetricer) EXPECT() *MockMetricer_Expecter {
	return &MockMetricer_Expecter{mock: &_m.Mock}
}

// MTLAPGaugeInc provides a mock function with given fields: p
func (_m *MockMetricer) MTLAPGaugeInc(p MTLAPGaugeParams) {
	_m.Called(p)
}

// MockMetricer_MTLAPGaugeInc_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MTLAPGaugeInc'
type MockMetricer_MTLAPGaugeInc_Call struct {
	*mock.Call
}

// MTLAPGaugeInc is a helper method to define mock.On call
//   - p MTLAPGaugeParams
func (_e *MockMetricer_Expecter) MTLAPGaugeInc(p interface{}) *MockMetricer_MTLAPGaugeInc_Call {
	return &MockMetricer_MTLAPGaugeInc_Call{Call: _e.mock.On("MTLAPGaugeInc", p)}
}

func (_c *MockMetricer_MTLAPGaugeInc_Call) Run(run func(p MTLAPGaugeParams)) *MockMetricer_MTLAPGaugeInc_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(MTLAPGaugeParams))
	})
	return _c
}

func (_c *MockMetricer_MTLAPGaugeInc_Call) Return() *MockMetricer_MTLAPGaugeInc_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockMetricer_MTLAPGaugeInc_Call) RunAndReturn(run func(MTLAPGaugeParams)) *MockMetricer_MTLAPGaugeInc_Call {
	_c.Call.Return(run)
	return _c
}

// MTLAPGaugeReset provides a mock function with given fields:
func (_m *MockMetricer) MTLAPGaugeReset() {
	_m.Called()
}

// MockMetricer_MTLAPGaugeReset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MTLAPGaugeReset'
type MockMetricer_MTLAPGaugeReset_Call struct {
	*mock.Call
}

// MTLAPGaugeReset is a helper method to define mock.On call
func (_e *MockMetricer_Expecter) MTLAPGaugeReset() *MockMetricer_MTLAPGaugeReset_Call {
	return &MockMetricer_MTLAPGaugeReset_Call{Call: _e.mock.On("MTLAPGaugeReset")}
}

func (_c *MockMetricer_MTLAPGaugeReset_Call) Run(run func()) *MockMetricer_MTLAPGaugeReset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMetricer_MTLAPGaugeReset_Call) Return() *MockMetricer_MTLAPGaugeReset_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockMetricer_MTLAPGaugeReset_Call) RunAndReturn(run func()) *MockMetricer_MTLAPGaugeReset_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMetricer creates a new instance of MockMetricer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMetricer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMetricer {
	mock := &MockMetricer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
